import { MantineProvider } from "@mantine/core";
import "./globals.css";
import Global from "./components/Global";

export const metadata = {
  title: "Lyon Cars Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Global>{children}</Global>
      </body>
    </html>
  );
}
